branches: main
tagFormat: v${version}
plugins:
- - '@semantic-release/commit-analyzer'
  - preset: conventionalcommits
- '@semantic-release/release-notes-generator'
- - '@semantic-release/changelog'
  - preset: conventionalcommits
    changelogFile: CHANGELOG.md
- - '@semantic-release/npm'
    - npmPublish: false
      pkgRoot: Assets/Flare.Logging
      tagFormat: v${version}
- - '@semantic-release/git'
  - assets:
    - Assets/Flare.Logging/package.json
    - CHANGELOG.md
    message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
- '@semantic-release/github'
