name: Update and Publish UPM Branch

on:
  push:
    branches:
      - main

jobs:
  perform-release:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Install conventional commits dependencies
          run: |
            yarn add -D conventional-changelog-conventionalcommits@5

        - name: Semantic release
          id: semantic
          uses: cycjimmy/semantic-release-action@v4.1.0
          with:
            extra_plugins: |
              conventional-changelog-conventionalcommits@v5
              @semantic-release/changelog
              @semantic-release/git
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Clean Up Checkout
          run: git clean -d -f

        - name: Update UPM branch
          if: steps.semantic.outputs.new_release_published == 'true'
          uses: hecomi/create-upm-branch-action@main
          with:
            git-tag: v${{ steps.semantic.outputs.new_release_version }}
            pkg-root-dir-path: Assets/Packages/com.REPLACE_ME_COMPANY_NAME.REPLACE_ME_PACKAGE_NAME

        - name: Create Github Release
          run: gh release create upm@$TAG --title "$TAG" --target "upm@$TAG" --notes "${NOTES}"
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NOTES: ${{ steps.semantic.outputs.new_release_notes }}
            TAG: v${{ steps.semantic.outputs.new_release_version }}
